#!/bin/sh

set -e

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case "$1" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/parted
copy_exec /sbin/findfs
copy_exec /sbin/resize2fs
copy_exec /sbin/e2fsck
copy_exec /sbin/blockdev
copy_exec /usr/bin/realpath
copy_exec /usr/bin/dirname
